/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import { DoubleSide } from "three";

export function GradientScene(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/GradientScene.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["CharacterArmature|Wave"].play();
    Object.values(materials).forEach((material) => {
      material.side = DoubleSide;
    });
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" position={[0, -0.33, 0]}>
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
            <skinnedMesh
              castShadow
              name="Arms"
              geometry={nodes.Arms.geometry}
              material={materials.GradientsMaterial}
              skeleton={nodes.Arms.skeleton}
            />
            <group name="Body_1">
              <skinnedMesh
                castShadow
                name="Body_2"
                geometry={nodes.Body_2.geometry}
                material={materials.GradientsMaterial}
                skeleton={nodes.Body_2.skeleton}
              />
              <skinnedMesh
                castShadow
                name="Body_3"
                geometry={nodes.Body_3.geometry}
                material={materials.Main2}
                skeleton={nodes.Body_3.skeleton}
              />
            </group>
            <skinnedMesh
              castShadow
              name="Ears"
              geometry={nodes.Ears.geometry}
              material={materials.GradientsMaterial}
              skeleton={nodes.Ears.skeleton}
            />
            <group name="Head_1">
              <skinnedMesh
                castShadow
                name="Head_2"
                geometry={nodes.Head_2.geometry}
                material={materials.GradientsMaterial}
                skeleton={nodes.Head_2.skeleton}
              />
              <skinnedMesh
                castShadow
                name="Head_3"
                geometry={nodes.Head_3.geometry}
                material={materials.EyeColor}
                skeleton={nodes.Head_3.skeleton}
              />
              <skinnedMesh
                castShadow
                name="Head_4"
                geometry={nodes.Head_4.geometry}
                material={materials.White}
                skeleton={nodes.Head_4.skeleton}
              />
              <skinnedMesh
                castShadow
                name="Head_5"
                geometry={nodes.Head_5.geometry}
                material={materials.Black}
                skeleton={nodes.Head_5.skeleton}
              />
            </group>
          </group>
        </group>
        <mesh
          name="Cube003_Cube002"
          receiveShadow
          castShadow
          geometry={nodes.Cube003_Cube002.geometry}
          material={materials.GradientsMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/GradientScene.glb");
